# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('rpmi_plaform_driver', src, depend = ['RT_USING_LIBRPMI', 'SOC_SPACEMIT_K2'], CPPPATH = CPPPATH)

Return('group')
