# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('Drivers_rproc', src, depend = ['BSP_USING_RPMSG'], CPPPATH = CPPPATH)

Return('group')
