# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

if GetDepend('BSP_RPROC_TEST') == False:
    SrcRemove(src, ['rproc-test_esos.c'])

SrcRemove(src, ['rproc-test_linux.c'])

group = DefineGroup('Drivers_rproc', src, depend = ['BSP_USING_RPMSG'], CPPPATH = CPPPATH)

Return('group')
