from building import *

# The set of source files associated with this SConscript file.
src = Split('''
rpmsg_services.c
''')
cwd = GetCurrentDir()
CPPPATH = [cwd]

group = DefineGroup('OpenAMPSrcAppsRpmsgService', src, depend = ['RT_USING_RPMSG_SERVICE'], CPPPATH = CPPPATH)

Return('group')

