# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

if GetDepend('SOC_SPACEMIT_K1_X') == False:
    SrcRemove(src, ['k1x_pm.c'])

group = DefineGroup('Drivers_pm', src, depend = ['BSP_USING_PM'], CPPPATH = CPPPATH)

Return('group')
