# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('Drivers_pm', src, depend = ['BSP_USING_PM'], CPPPATH = CPPPATH)

Return('group')
