# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('MAILBOXDrivers', src, depend = ['BSP_USING_MAILBOX'], CPPPATH = CPPPATH)

Return('group')
