# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('CCUDrivers', src, depend = ['RT_USING_CLK'], CPPPATH = CPPPATH)

Return('group')
