# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

if GetDepend('BSP_PWM_TEST') == False:
    SrcRemove(src, ['pwm-test.c'])


group = DefineGroup('Drivers_pwm', src, depend = ['BSP_USING_PWM'], CPPPATH = CPPPATH)

Return('group')
