Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

group   = DefineGroup('drv_ir', src, depend = ['BSP_USING_IR'], CPPPATH = CPPPATH)

Return('group')
