#!/bin/sh
set -e

PREREQ=""

prereqs() {
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

for f in /usr/lib/riscv64-linux-gnu/esos/rt24_os0_rcpu.elf /usr/lib/riscv64-linux-gnu/esos/rt24_os1_rcpu.elf; do
    if [ -f "$f" ]; then
        echo "Including $f in initramfs" >&2
        copy_file firmware "$f" "/lib/firmware/$(basename "$f")"
    else
        echo "WARNING: $f not found on host" >&2
    fi
done
