# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

if GetDepend('BSP_GPIO_TEST') == False:
    SrcRemove(src, ['gpio-test.c'])

group = DefineGroup('drvgpio', src, depend = ['BSP_USING_GPIO'], CPPPATH = CPPPATH)

Return('group')
