# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('Gpio', src, depend = ['BSP_USING_GPIO'], CPPPATH = CPPPATH)

objs = [group]

if GetDepend(['BSP_USING_GPIO']):
	list = os.listdir(cwd)
	for item in list:
		if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
			objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
