# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

# Add include path for librpmi headers
CPPPATH += [os.path.join(Dir('#').abspath, 'components/librpmi/include')]

group = DefineGroup('RPMIDrivers', src, depend = ['BSP_USING_MAILBOX', 'RT_USING_LIBRPMI'], CPPPATH = CPPPATH)

# search in the file system implementation
list = os.listdir(cwd)

if GetDepend('RT_USING_LIBRPMI'):
	for item in list:
		if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
			group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
