# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

if GetDepend('BSP_HWTIMER_TEST') == False:
    SrcRemove(src, ['hwtimer-test.c'])

group = DefineGroup('HWtimerDrivers', src, depend = ['BSP_USING_HWTIMER'], CPPPATH = CPPPATH)

Return('group')
