# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('HWtimerDrivers', src, depend = ['BSP_USING_HWTIMER'], CPPPATH = CPPPATH)

Return('group')
