# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

if GetDepend('BSP_PIN_WAKEUP_TEST') == False:
    SrcRemove(src, ['pinctrl-test-wakeup.c'])

group = DefineGroup('drvpinctrl', src, depend = ['BSP_USING_PIN'], CPPPATH = CPPPATH)

Return('group')
